version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:current

jobs:
  test:
    executor: base
    steps:
      - checkout
      - run:
          name: Run command
          command: git branch -a

workflows:
  main:
    jobs:
      - test:
        filters:
          branches:
            only:
              main

