version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:current

jobs:
  test:
    executor: base
    steps:
      - run:
          name: Run command
          command: echo 'hello world'

workflows:
  main:
    jobs:
      - test
